#############################################################################
# Makefile for building: Test_Bench
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  ../Test_Bench/Test_Bench.pro
# Template: app
# Command: /opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Test_Bench/Test_Bench.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../Test_Bench -I. -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5 -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork -isystem /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore -I. -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Test_Bench1.0.0
DISTDIR = /home/forlinx/build-Test_Bench-okg2l-Debug/.tmp/Test_Bench1.0.0
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS)
LIBS          = $(SUBLIBS) -lQt5Quick -L/mnt/renesas/vlp/build/tmp/work/aarch64-poky-linux/qtdeclarative/5.6.3+gitAUTOINC+bb01612a88-r0/recipe-sysroot/usr/lib -lQt5Gui -L/mnt/renesas/vlp/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/recipe-sysroot/usr/lib -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
SED           = sed
STRIP         = $(OE_QMAKE_STRIP)

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Test_Bench/main.cpp \
		../Test_Bench/can.cpp \
		../Test_Bench/votol.cpp qrc_qml.cpp \
		moc_can.cpp
OBJECTS       = main.o \
		can.o \
		votol.o \
		qrc_qml.o \
		moc_can.o
DIST          = /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/linux.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/qconfig.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resources.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/moc.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/lex.prf \
		../Test_Bench/Test_Bench.pro ../Test_Bench/can.h \
		../Test_Bench/votol.h ../Test_Bench/main.cpp \
		../Test_Bench/can.cpp \
		../Test_Bench/votol.cpp
QMAKE_TARGET  = Test_Bench
DESTDIR       = 
TARGET        = Test_Bench


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Test_Bench/Test_Bench.pro /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/linux.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/qconfig.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resources.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/moc.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/lex.prf \
		../Test_Bench/Test_Bench.pro \
		../Test_Bench/qml.qrc \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Quick.prl \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Gui.prl \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Qml.prl \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Network.prl \
		/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Core.prl
	$(QMAKE) -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Test_Bench/Test_Bench.pro
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/unix.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/linux.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/qconfig.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/default_post.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/qt.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/resources.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/moc.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/yacc.prf:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/features/lex.prf:
../Test_Bench/Test_Bench.pro:
../Test_Bench/qml.qrc:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Quick.prl:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Gui.prl:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Qml.prl:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Network.prl:
/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Test_Bench/Test_Bench.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Test_Bench/qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Test_Bench/can.h ../Test_Bench/votol.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Test_Bench/main.cpp ../Test_Bench/can.cpp ../Test_Bench/votol.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: ../Test_Bench/qml.qrc \
		../Test_Bench/main.qml
	/opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/rcc -name qml ../Test_Bench/qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_can.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_can.cpp
moc_can.cpp: ../Test_Bench/can.h
	/opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/moc $(DEFINES) -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/lib64/qt5/mkspecs/linux-oe-g++ -I/home/forlinx/Test_Bench -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5 -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore -I. -I/opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/lib/aarch64-poky-linux/gcc/aarch64-poky-linux/8.3.0/include -I/opt/poky/3.1.21/sysroots/x86_64-pokysdk-linux/lib/aarch64-poky-linux/gcc/aarch64-poky-linux/8.3.0/include-fixed -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0 -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0/aarch64-poky-linux -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0/backward -I/opt/poky/3.1.21/sysroots/aarch64-poky-linux/usr/include ../Test_Bench/can.h -o moc_can.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: ../Test_Bench/main.cpp ../Test_Bench/can.h \
		../Test_Bench/votol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Test_Bench/main.cpp

can.o: ../Test_Bench/can.cpp ../Test_Bench/can.h \
		../Test_Bench/votol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o can.o ../Test_Bench/can.cpp

votol.o: ../Test_Bench/votol.cpp ../Test_Bench/votol.h \
		../Test_Bench/can.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o votol.o ../Test_Bench/votol.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_can.o: moc_can.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_can.o moc_can.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Test_Bench/bin || mkdir -p $(INSTALL_ROOT)/opt/Test_Bench/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Test_Bench/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Test_Bench/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Test_Bench/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

